/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Limites;

import Controladores.ControlePessoa;
import Entidades.Comprador;
import Entidades.Corretor;
import Entidades.Pessoa;
import Entidades.Vendedor;
import javax.swing.JFrame;

/**
 *
 * @author josia
 */
public class LimiteShowPessoas extends javax.swing.JFrame {
    
    private ControlePessoa objCtr;
    
    public LimiteShowPessoas(ControlePessoa objCtr) {
        this.objCtr = objCtr;
        initComponents();
        
        String saida="";
        for(Pessoa p : objCtr.getListaPessoas()){
            if(p instanceof Vendedor){
                saida+= "Nome: " + p.getNome() + "\nTipo: Vendedor\nCPF: " + p.getCpf() + "\nEmail: "+ p.getEmail() +"   Fone: "+ p.getFone();
            }
            if(p instanceof Corretor){
                saida+= "Nome: " + p.getNome() + "\nTipo: Corretor\nCPF: " + p.getCpf() + "\nEmail: "+ p.getEmail() +"   Fone: "+ p.getFone();
            }
            if(p instanceof Comprador){
                saida+= "Nome: " + p.getNome() + "\nTipo: Comprador\nCPF: " + p.getCpf() + "\nEmail: "+ p.getEmail() +"   Fone: "+ p.getFone();
            }
            
            saida+="\n\n";
        }
        
        jTextArea1.setText(saida);
        this.setTitle("Pessoas cadastradas");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
